[package]
name = "rtok_ts-analyzer"
version = "0.1.0"
edition = "2024"
authors = ["Ryota Konabe <rt.konabe@gmail.com>"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
