name: Publish to crates.io & npm

on:
  push:
    # TODO: PRがClosedされたときにpublishするようにする
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
      - name: Checkout code
        uses: actions/checkout@v4
      - run: git update-index --chmod=+x .github/scripts/check_cargo_version.sh
      - uses: ./.github/actions/build-and-test
      - name: Login to crates.io
        run: cargo login ${{ secrets.CARGO_TOKEN }}
      - name: Check if version already exists on crates.io
        id: check_version_tarq_core
        run: |
          result=`.github/scripts/check_cargo_version.sh tarq_core`
          if [ "$result" == "true" ]; then
            echo "Version already exists."
          fi
          echo "exists=$result" >> "$GITHUB_OUTPUT"
      - name: Publish tarq_core
        if: steps.check_version_tarq_core.outputs.exists == 'false'
        run: cargo publish --verbose --manifest-path tarq_core/Cargo.toml
      - name: Check if version already exists on crates.io
        id: check_version_tarq
        run: |
          result=`.github/scripts/check_cargo_version.sh  tarq`
          if [ "$result" == "true" ]; then
            echo "Version already exists."
          fi
          echo "exists=$result" >> "$GITHUB_OUTPUT"
      - name: Publish tarq
        if: steps.check_version_tarq.outputs.exists == 'false'
        run: cargo publish --verbose --manifest-path tarq/Cargo.toml
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build npm project
        run: wasm-pack build tarq_core --release --target nodejs
      - name: Publish to npm
        run: |
          if npx can-npm-publish --verbose tarq_core/pkg; then
              wasm-pack publish
          else
              echo "publish skipped"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
