name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install wasm-pack
        run: cargo install wasm-pack
      - name: Build the project
        run: wasm-pack build --release
      - run: |
          echo "${{ secrets.NPM_TOKEN }}"
      - name: Publish to npm
        run: npm publish pkg --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
