name: Publish to crates.io & npm

on:
  push:
    # TODO: PRがClosedされたときにpublishするようにする
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-and-test
